Assets/Resource.meta, Assets/Scenes/MainScene.unity, Assets/Scenes/MainScene.unity.meta, Assets/Scripts.meta, Assets/Scripts/Manager.meta, Assets/Scripts/Skill.meta, Assets/Scripts/Skill/EffectData.cs, Assets/Scripts/Skill/EffectData.cs.meta, Assets/Scripts/Skill/SO_Effect.meta, Assets/Scripts/Skill/SO_Effect/Attack.asset, Assets/Scripts/Skill/SO_Effect/Attack.asset.meta, Assets/Scripts/Skill/SO_Skill.meta, Assets/Scripts/Skill/SO_Skill/FireBall.asset, Assets/Scripts/Skill/SO_Skill/FireBall.asset.meta, Assets/Scripts/Skill/SkillData.cs, Assets/Scripts/Skill/SkillData.cs.meta, Assets/Scripts/Unit.meta, Assets/Scripts/Unit/SO_Unit.meta, Assets/Scripts/Unit/SO_Unit/TestUnit01.asset, Assets/Scripts/Unit/SO_Unit/TestUnit01.asset.meta, Assets/Scripts/Unit/TotalUnitData.cs, Assets/Scripts/Unit/TotalUnitData.cs.meta, Assets/Scripts/Unit/Unit.cs, Assets/Scripts/Unit/Unit.cs.meta, Assets/Scripts/Unit/UnitData.cs, Assets/Scripts/Unit/UnitData.cs.meta, ProjectSettings/ProjectSettings.asset
유닛 데이터 및 SO
스킬 데이터 및 SO
이펙트 데이터 및 SO
=> 유닛, 스킬, 이펙트 데이터 추가

Assets/Scenes/SampleScene.unity, Assets/Script/Manager/GameManager.cs, Assets/Script/UI/TurnChange.cs, Assets/Script/UI/TurnChange.cs.meta, Packages/manifest.json, Packages/packages-lock.json, ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt, ProjectSettings/SceneTemplateSettings.json
=> Add TurnChange Button

Assets/Image/Background-1.png.meta, Assets/Scenes/HM Scene 1.unity, Assets/Scenes/HM Scene 1.unity.meta, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/UI/UI_PhaseChange.cs, Assets/Script/Unit/Unit_AI_Controller.cs, Assets/Script/Unit/Unit_AI_Controller.cs.meta, ProjectSettings/ProjectSettings.asset
전략 패턴으로 사용가능하도록 AI controller를 만들었습니다.
변수명은 임시로 짰으니 다시 수정하면 되겠습니다
=> Ai controller 스크립트 추가

Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/Unit_AI_Controller.cs
=> Ai controller 함수 수정

Assets/Script/ClassDiagram1.cd, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/GameManager.cs, Assets/Script/UI/UI_PhaseChange.cs
=> Phase Update 함수 수정

Assets/Script/ScriptableObject/UnitDataSO.cs
EngagePhase진입 시 전투를 진행하지 않던 버그 수정
=> Engage Phase 버그 수정

Assets/Etc File/Etc/TEST.cs, Assets/Etc File/Etc/TEST.cs.meta, Assets/Scenes/Battle.unity
This reverts commit b587f8ed0acbf683025ef215673327b9a2ad33e0.
=> Revert "feature : TEST 유닛 생성 태스트 삭제"

Assets/Animation/TestSlime/Enemy_Slime2_0.controller, Assets/Resources/ScriptableObject/UnitDataSO/Test.asset, Assets/Resources/ScriptableObject/UnitDataSO/검병.asset, Assets/Resources/ScriptableObject/UnitDataSO/궁수.asset, Assets/Resources/ScriptableObject/UnitDataSO/사제.asset, Assets/Resources/ScriptableObject/UnitDataSO/암살자.asset, Assets/Resources/ScriptableObject/UnitDataSO/여동생.asset, Assets/Resources/ScriptableObject/UnitDataSO/오빠.asset, Assets/Script/CutScene/CutSceneController.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/BattleManager/PhaseState/ActionPhase.cs, Assets/Script/Manager/BattleManager/PhaseState/EngagePhase.cs, Assets/Script/ScriptableObject/UnitDataSO.cs, Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/SplashUnitAIController.cs, Assets/Script/Unit/UnitSpawner.cs
=> Animation bug fix

Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial1.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial2.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial3.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial4.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial5.prefab, Assets/Scenes/Battle.unity, Assets/Scenes/TutorialScene.unity, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/GameManager.cs, Assets/Script/SceneChanger.cs, Assets/Script/Scenes/BattleScene.cs
=> 튜토리얼 배틀씬에 추가

.github/.workflow/Build.yml
=> Build CI 추가

.github/workflows/Build.yml
Build CI의 Path를 변경합니다.
Build가 잘 동작하는 지 확인
=> Build CI Path 변경

Assets/Script/SceneChanger.cs, Assets/Script/Stage/StageChanger.cs
Battle에서 BattleScene으로 수정
> Scene 이름 변화에 따른 오류 수정. (Battle에서 BattleScene)
> 로컬에서 실행
=> fix : Scene 이름 변화에 따른 오류 수정

Assets/Script/Field/Mana.cs, Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/BattleManager/BattleUIManager.cs, Assets/Script/Manager/BattleManager/BattleUIManager.cs.meta, Assets/Script/Manager/BattleManager/PhaseState/ActionPhase.cs, Assets/Script/Manager/BattleManager/PhaseState/EngagePhase.cs, Assets/Script/Manager/BattleManager/PhaseState/MovePhase.cs, Assets/Script/Manager/BattleManager/PhaseState/PreparePhase.cs, Assets/Script/UI/Scene/UI_Hands.cs, Assets/Script/UI/Scene/UI_TurnCount.cs
> BattleManager 및 BattleDataManager 코드 중에서 UI 관련된 코드를 BattleUIManager로 분리하고, 이로 인해 발생한 경로 오류 수정
> 로컬에서 실행.
=> BattleManager 및 BattleDataManager의 코드를 BattleUIManager로 분리

Assets/Resources/Prefabs/UI/Popup/UI_StigmaSelectButton.prefab, Assets/Script/EventScene/StigmaStore.cs, Assets/Script/UI/Popup/UI_StigmaSelectButton.cs, Assets/Script/Unit/DeckUnit.cs
> 낙인의 구조를 변경하면서 바뀐 부분을 수정했습니다.
> 낙인소에서 실행해서 확인
=> 낙인 이미지, 설명 가져오는 부분 수정

Assets/Script/Manager/BattleManager/BattleManager.cs
> 첫 턴 할인가가 적용 안 되는 버그를 수정했습니다.
> Battle Scene 내에서 적용되는 것 확인했습니다.
=> fix : 첫 턴 할인가 적용

Assets/Resources/Prefabs/UI/Scene/UI_Info.prefab
> Prefab 삭제로 인한 오류 수정
> 로컬에서 실행
=> fix : 오류 수정

Assets/Resources/Prefabs/@GameManager.prefab, Assets/Script/Manager/GameManager.cs
inputmanager가 두개 선언되려고 하는 문제가 생겨 serialized field를 통해 inputmanager 집어넣었습니다.
이를 통해 빌드가 만들어지도록 했습니다
로컬
PR해서 빌드 오류가 뜨는지 확인
=> inputmanager 오류 수정

Assets/Resources/Prefabs/UI/Scene/UI_ControlBar.prefab, Assets/Resources/Prefabs/UI/Sub/PlayerSkillCard.prefab, Assets/Script/Data/DataManager.cs, Assets/Script/Field/Field.cs, Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/UI/Scene/UI_PlayerSkill.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillBounce.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillBounce.cs.meta, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillHeal.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillHeal.cs.meta, Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/Passvie/가학.cs, Assets/Script/Unit/Passvie/고양.cs
힐, 바운스 추가
> 전반적인 플레이서 스킬 작동 방식을 변경, Heal, Bounce 기능 추가. 그에 따라 데이터가 변경되어서 유지되는 문제 해결을 위한 전체적인 스탯 방식 수정
> 로컬에서 실행
=> feature : 플레이어 스킬 2개 추가

Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/BattleManager/PlayerSkillControler.cs, Assets/Script/Manager/BattleManager/PlayerSkillControler.cs.meta, Assets/Script/UI/Popup/UI_TextHover.cs, Assets/Script/UI/Scene/UI_Hands.cs, Assets/Script/UI/Scene/UI_PlayerSkill.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkill.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillBounce.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillDamage.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillHeal.cs, Assets/Script/UI/Sub/PlayerSkill/PlayerSkillWhisper.cs, Assets/Script/Utils/Define.cs
> 플레이어 스킬과 연관된 코드를 분리, 일부 오타 수정
> 로컬에서 실행
=> 플레이어 스킬 분리

Assets/Script/Unit/SplashUnitAIController.cs, Assets/Script/Unit/UnitAIController_lagacy2.cs, Assets/Script/Unit/UnitAIController_lagacy2.cs.meta
> AI를 수정하여 보다 보편적인 AI로 수정, 기존 코드 보존
> 로컬에서 실행
=> feature : AI 수정

Assets/Resources/ScriptableObject/UnitDataSO/오리지널/흑기사.asset, Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/BattleManager/PhaseState/PreparePhase.cs, Assets/Script/Unit/DeckUnit.cs
> 스탯 시스템 리팩토링을 기반으로 첫 턴 유닛 코스트 할인 시스템 적용
> 로컬에서 실행
=> 첫 턴에 유닛 코스트 할인 적용

Assets/Resources/Prefabs/Passive/가학1.prefab, Assets/Resources/Prefabs/Passive/가학2.prefab, Assets/Resources/Prefabs/Passive/강림.prefab, Assets/Resources/Prefabs/Passive/고문관.prefab, Assets/Resources/Prefabs/Passive/대죄.prefab, Assets/Resources/Prefabs/Passive/동생.prefab, Assets/Resources/Prefabs/Passive/망령.prefab, Assets/Resources/Prefabs/Passive/오빠.prefab, Assets/Resources/Prefabs/Passive/자애.prefab, Assets/Resources/Prefabs/Passive/처형.prefab, Assets/Resources/Prefabs/Passive/흡수.prefab
> 변수명 수정에 따라 깨진 프리팹 수정, 대죄는 공격 전에 부여해야하고 처형은 공격 후에 체크해야해서 수정
> 로컬에서 실행
=> 깨진 낙인 프리팹 수정 + 타이밍 오류 수정

Assets/Resources/Prefabs/UI/Scene/EventScene/UI_harlot.prefab, Assets/Script/Scenes/EventScene/HarlotScene/HarlotSceneController.cs
eventscene의 harlot에서 낙인 부여 기능을 추가했습니다. 유닛 생성은 애니메이션이 없고 기능도 없어서 추후 추가할 예정입니다.
로컬
=> harlot 프리팹 및 controller 기능 추가

Assets/Resources/Data/Drictionary.json, Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/Buff/Buff.cs, Assets/Script/Unit/Buff/Buff_AttackUp.cs, Assets/Script/Unit/Buff/Buff_Benediction.cs, Assets/Script/Unit/Buff/Buff_Benediction.cs.meta, Assets/Script/Unit/Buff/Buff_Bleeding.cs, Assets/Script/Unit/Buff/Buff_Encourage.cs, Assets/Script/Unit/Buff/Buff_Sadism.cs, Assets/Script/Unit/UnitSpawner.cs, Assets/Script/Utils/Define.cs
> 신성 버프를 추가하고, 매니저 및 배틀유닛을 리팩토링해 버프 및 낙인 관련을 배틀 유닛 내에서만 처리하게 수정
> 로컬에서 실행
=> 신성 버프 추가 및 관련 구조 리팩토링

Assets/Script/Unit/Buff/Buff.cs, Assets/Script/Unit/Buff/Buff_AttackUp.cs, Assets/Script/Unit/Buff/Buff_Benediction.cs, Assets/Script/Unit/Buff/Buff_Bleeding.cs, Assets/Script/Unit/Buff/Buff_Crime.cs, Assets/Script/Unit/Buff/Buff_Crime.cs.meta, Assets/Script/Unit/Buff/Buff_Encourage.cs, Assets/Script/Unit/Buff/Buff_Sadism.cs, Assets/Script/Utils/Define.cs
> 죄악 버프 추가, 버프에 해제풀가인지 구별하는 변수 추가
> 로컬에서 실행
=> 죄악 버프 추가, 해제풀가 변수 추가

Assets/Scenes/BattleScene.unity, Assets/Script/Data/DataManager.cs, Assets/Script/Manager/BattleManager/BattleCutSceneController.cs, Assets/Script/Manager/BattleManager/CameraHandler.cs, Assets/Script/Scenes/StageSelectScene/StageChanger.cs, Assets/Script/Unit/BattleUnit.cs
- 유닛의 공격 시 이펙트를 기울기에서 흔들리는걸로 변경
=> 이펙트 변경 및 stage 임시 변경

Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/Buff/Buff.cs, Assets/Script/Unit/Buff/Buff_AttackUp.cs, Assets/Script/Unit/Buff/Buff_Benediction.cs, Assets/Script/Unit/Buff/Buff_Bleeding.cs, Assets/Script/Unit/Buff/Buff_Crime.cs, Assets/Script/Unit/Buff/Buff_Encourage.cs, Assets/Script/Unit/Buff/Buff_Sadism.cs, Assets/Script/Unit/UnitBuff.cs
> 버프에 caster 변수 추가를 추가해 버프를 건 유닛을 저장
> 로컬에서 실행
=> feature : 버프에 caster 변수 추가

Assets/Script/Field/Field.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/BattleManager/BattleUIManager.cs, Assets/Script/Manager/BattleManager/PhaseState/ActionPhase.cs, Assets/Script/Manager/BattleManager/PhaseState/EndPhase.cs, Assets/Script/Manager/BattleManager/PhaseState/EngagePhase.cs, Assets/Script/Manager/BattleManager/PhaseState/MovePhase.cs, Assets/Script/Manager/BattleManager/PhaseState/Phase.cs, Assets/Script/Manager/BattleManager/PhaseState/PhaseController.cs, Assets/Script/Manager/BattleManager/PhaseState/PreparePhase.cs, Assets/Script/Manager/BattleManager/PlayerSkillController.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Bounce.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Damage.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Heal.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Whisper.cs, Assets/Script/UI/PlayerSkill/UltimatePlayerSkill_Whisper.cs, Assets/Script/Unit/Stigma/Stigma_Gamble.cs.meta, Assets/Script/Utils/Define.cs
> 필드, 페이즈, 배틀매니져를 리팩토링
> 로컬에서 실행
=> 필드 및 페이즈 리팩토링

Assets/Resources/Prefabs/PlayerSkill/PlayerSkill_Damage.prefab, Assets/Resources/Prefabs/PlayerSkill/PlayerSkill_DarkCross.prefab, Assets/Resources/Prefabs/PlayerSkill/PlayerSkill_DarkCross.prefab.meta, Assets/Resources/Prefabs/PlayerSkill/PlayerSkill_Whisper.prefab, Assets/Resources/ScriptableObject/Incarna/Incarna.asset, Assets/Script/Field/Field.cs, Assets/Script/ScriptableObject/Incarna.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Cross.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Cross.cs.meta
> 
- 적 지정, 필드 끝까지 십자범위 안에 있는 적 유닛에게만 15데미지 가하기
- 보유한 마나 초과 사용시에도 스킬 사용 후 0으로 처리
> 로컬에서 테스트 완료
=> 검은 십자가 스킬 구현

Assets/Script/UI/Scene/UI_PlayerSkill.cs, Assets/Script/Utils/Define.cs
=> 플레이어 스킬 마나 오류 수정

Assets/Resources/Prefabs/Stigma/Stigma_Gamble.prefab, Assets/Resources/Video/IntroVideo.mp4.meta, Assets/Resources/Video/IntroVideo.renderTexture, Assets/Scenes/CutScene.unity, Assets/Script/Field/Mana.cs, Assets/Script/Unit/Stigma/Stigma_Gamble.cs.meta
인트로 영상 오류 수정 및 겜블 missing 수정
로컬테스트
=> 인트로 영상 오류 및 겜블 낙인 오류 수정

Assets/Script/Field/Mana.cs, Assets/Script/Manager/BattleManager/BattleUIManager.cs, Assets/Script/Manager/BattleManager/PhaseState/ActionPhase.cs, Assets/Script/Manager/BattleManager/PhaseState/BattleOverPhase.cs, Assets/Script/Manager/BattleManager/PhaseState/MovePhase.cs, Assets/Script/Manager/BattleManager/PhaseState/PhaseController.cs, Assets/Script/Manager/BattleManager/PhaseState/PreparePhase.cs, Assets/Script/UI/Scene/UI_TurnNotify.cs, Assets/Script/Unit/Buff/Buff_Immortal.cs
> 턴 알림이 겹치지 않게 UI를 수정
> 로컬에서 실행
=> 턴 알림이 겹치지 않게 수정

Assets/Resources/Prefabs/UI/Scene/UI_ControlBar.prefab, Assets/Resources/Prefabs/UI/Scene/UI_DeckButton.prefab, Assets/Resources/Prefabs/UI/Scene/UI_Info.prefab, Assets/Resources/Prefabs/UI/Scene/UI_OptionButton.prefab, Assets/Resources/Prefabs/UI/Scene/UI_TurnChangeButton.prefab, Assets/Resources/Prefabs/UI/Sub/HandCard.prefab, Assets/Resources/ScriptableObject/Incarna/Incarna.asset, Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Manager/BattleManager/BattleUIManager.cs, Assets/Script/UI/Sub/UI_Hand.cs
배틀씬에서 사용하는 UI를 새롭게 이미지를 바꿔 대체했습니다
추가로 사용하지 않는 TurnCount를 주석처리했습니다.
로컬테스트
=> 배틀씬 UI 수정 완료

Assets/Scenes/StageSelectScene 1.unity.meta, Assets/Scenes/StageSelectScene.unity, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Scenes/StageSelectScene/StageCameraController.cs
=> 스테이지 선택 신 수정

Assets/Script/UI/Popup/UI_ESCOption.cs
=> ESC 옵션 오류 수정

Assets/Script/Manager/BattleManager/PhaseState/PreparePhase.cs, Assets/Script/UI/Scene/UI_PlayerSkill.cs, Assets/Script/UI/Scene/UI_TurnChangeButton.cs
> 스킬 첫 턴 부터 사용 가능
> 로컬에서 테스트 완료
=> 스킬 첫 턴 부터 사용 가능

Assets/Resources/Arts/StageSelect/BackLight/CommonBattle.png.meta, Assets/Resources/Arts/StageSelect/BackLight/EliteBattle_0.png.meta, Assets/Resources/Arts/StageSelect/BackLight/StigmaStore.png.meta, Assets/Resources/Arts/StageSelect/BackLight/UpgradeStore.png.meta, Assets/Resources/Arts/StageSelect/BackLight/_Temp.png.meta, Assets/Resources/Arts/StageSelect/Node/CommonBattle.png.meta, Assets/Resources/Arts/StageSelect/Node/EliteBattle_0.png.meta, Assets/Resources/Arts/StageSelect/Node/StigmaStore.png.meta, Assets/Resources/Arts/StageSelect/Node/UpgradeStore.png.meta, Assets/Resources/Arts/StageSelect/Node/_Temp.png.meta, Assets/Resources/Prefabs/@GameManager.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial14.prefab, Assets/Resources/Prefabs/UI/Popup/UI_UnitInfo.prefab, Assets/Resources/Prefabs/UI/Scene/UI_ControlBar.prefab, Assets/Resources/Prefabs/UI/Sub/HandCard.prefab, Assets/Resources/ScriptableObject/Incarna/Incarna.asset, Assets/Resources/ScriptableObject/UnitDataSO/괴인.asset, Assets/Resources/ScriptableObject/UnitDataSO/노동자.asset, Assets/Scenes/BattleScene.unity, Assets/Scenes/CutScene.unity, Assets/Scenes/EndingCreditScene.unity, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/UI/Fixed.cs, Assets/Script/UI/Fixed.cs.meta, Assets/Script/UI/Popup/UI_UnitInfo.cs, Assets/Script/UI/Scene/UI_PlayerSkill.cs, Assets/Script/UI/Scene/UI_UnitCard.cs, Assets/Script/UI/Sub/UI_Hand.cs
대화스크립트 수정
해상도 고정 수정
UI 카드 수정
UI_UnitInfo는 유닛 초상화 대신 애니메이션이 뜨도록 하겠습니다
로컬테스트
=> UI 카드 수정, 해상도 수정

Assets/Plugins/IngameDebugConsole/IngameDebugConsole.prefab, Assets/Resources/Prefabs/@GameManager.prefab, Assets/Scenes/CutScene.unity, Assets/Scenes/EndingCreditScene.unity, Assets/Scenes/EventScene.unity, Assets/Scenes/LogoScene.unity, Assets/Scenes/MainScene.unity, Assets/Scenes/StageSelectScene.unity
=> 게임 매니저 비활성화 수정

Assets/Resources/Prefabs/UI/Scene/UI_Info.prefab, Assets/Script/UI/Popup/UI_Info.cs, Assets/Script/UI/Sub/UI_StigmaDescription.cs
=> 유닛버튼 호버 오류 수정

Assets/Resources/Arts/EffectAnimation/New Animation.anim, Assets/Resources/Prefabs/@GameManager.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial1.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial10.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial11.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial12.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial13.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial14.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial2.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial3.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial4.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial5.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial6.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial7.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial8.prefab, Assets/Resources/Prefabs/UI/Popup/Tutorial/UI_Tutorial9.prefab, Assets/Scenes/BattleScene.unity, Assets/Scenes/EndingCreditScene.unity, Assets/Script/Manager/BattleManager/PhaseState/EngagePhase.cs, Assets/Script/Manager/GameManager.cs, Assets/Script/UI/Popup/UI_ESCOption.cs, Assets/Script/UI/Popup/UI_Tutorial.cs
> 
- 튜토리얼 일시정지 후 esc 누르면 진행되는 오류 해결
- GameObject 여러개 생기는 오류 해결
- 크레딧 씬 텍스트, 폰트, 애니메이션, grid 사이즈 변경
> 로컬에서 테스트 완료
=> 튜토리얼 Timescale 오류 해결

Assets/Script/UI/Scene/UI_Hands.cs, Assets/Script/UI/Scene/UI_PlayerSkill.cs, Assets/Script/UI/Scene/UI_TurnChangeButton.cs
=> 선택 관련 오류 수정

Assets/Animation/Effect/Animation/@UI_Root.controller, Assets/Animation/Effect/SpriteSheet/new/skill2-Sheet_0.controller, Assets/Resources/Arts/EffectAnimation/PlayerSkill/CrossThunder.anim, Assets/Resources/Prefabs/UI/Hover/UI_SkillHover.prefab, Assets/Resources/Prefabs/UI/Scene/UI_ControlBar.prefab, Assets/Resources/Prefabs/UI/Sub/PlayerSkillCard.prefab, Assets/Resources/ScriptableObject/Incarna/Incarna.asset, Assets/Script/Manager/BattleManager/BattleCutSceneController.cs, Assets/Script/UI/Hover/UI_SkillHover.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Cross.cs, Assets/Script/UI/PlayerSkill/PlayerSkill_Whisper.cs, Assets/Script/UI/Sub/UI_PlayerSkillCard.cs
> - 플스 피격시 피격 애니메이션 재생
- 플스 카드구성, 위치, 호버 변경
> 로컬테스트 완료
=> 플스 피격시 피격 애니메이션 재생

Assets/Resources/Prefabs/UI/Popup/UI_Conversation.prefab, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/UI/Popup/UI_Conversation.cs, Assets/Script/UI/Scene/UI_Hands.cs, Assets/Script/UI/Scene/UI_PlayerSkill.cs
> 검은 정수 오류 수정, 소환 시 딜레이
>로컬 테스트
=> 검은 정수 오류 수정

Assets/Resources/Prefabs/TestBlur.prefab, Assets/Script/Scenes/StageSelectScene/StageCameraController.cs, Assets/Script/UI/Sub/UI_Hand.cs
> 
- 맵씬 처음 진입시 카메라 내려오기
- 공격 카메라 배경 암전 강하게 변경
> 로컬 테스트 완료
=> 맵씬 처음 진입시 카메라 내려오기

Assets/Scenes/BattleScene.unity, Assets/Script/Scenes/StageSelectScene/Stage.cs, Assets/Script/Scenes/StageSelectScene/StageManager.cs, Assets/Script/Scenes/StageSelectScene/StageNodeBackLight.cs
> 
- 스테이지 노드 백라이트 반짝임 및 페이드인 페이드아웃 구현
- 튜토창보다 옵션창이 앞에 위치하게 변경
> 로컬 테스트 완료
=> 스테이지 노드 백라이트 깜빡이게 변경

Assets/Resources/Prefabs/Stigma/Stigma_Benevolence.prefab, Assets/Resources/Prefabs/Stigma/Stigma_DeathStrike.prefab, Assets/Resources/Prefabs/Stigma/Stigma_ImmortalⅠ.prefab, Assets/Resources/Prefabs/Stigma/Stigma_ImmortalⅡ.prefab, Assets/Resources/Prefabs/Stigma/Stigma_InvincibleⅠ.prefab, Assets/Resources/Prefabs/Stigma/Stigma_InvincibleⅡ.prefab, Assets/Resources/Prefabs/Stigma/Stigma_RaiseⅠ.prefab, Assets/Resources/Prefabs/Stigma/Stigma_RaiseⅡ.prefab, Assets/Resources/Prefabs/Stigma/Stigma_TailWind.prefab, Assets/Script/Field/Field.cs, Assets/Script/Field/Tile.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Scenes/BattleTestScene/BattleTestManager.cs, Assets/Script/Scenes/BattleTestScene/BattleTestUnit.cs, Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/Buff/Buff_Immortal.cs, Assets/Script/Utils/Define.cs
=> 장판, 타이밍 리팩토링

Assets/Resources/Prefabs/@GameManager.prefab, Assets/Resources/Prefabs/EffectTile/Nimrod_Attack_Enemy.prefab, Assets/Resources/Prefabs/UI/Popup/UI_ESCOption.prefab, Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Manager/GameManager.cs, Assets/Script/Manager/UIManager.cs, Assets/Script/UI/Popup/UI_ESCOption.cs, Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/UnitAction/UnitAction.cs, Assets/Script/Unit/UnitAction/UnitAction_Centaurus.cs, Assets/Script/Unit/UnitAction/UnitAction_Centaurus.cs.meta, Assets/Script/Unit/UnitAction/UnitAction_Nimrod.cs, Assets/Script/Unit/UnitAction/UnitAction_Trinity.cs, Assets/Script/Unit/UnitAction/UnitAction_Trinity.cs.meta, Assets/Script/Utils/Define.cs
> 삼신기, 켄타우로스를 추가. 단 행동 방식만이며, 이미지 등은 모두 미적용. 일시정지 버튼의 행동 방식을 수정해서, 2번 생기는 버그 수정
> 로컬 테스트
=> 삼신기, 켄타우로스 추가(기능만, 연출 등 미적용)

Assets/Resources/ScriptableObject/GameDataMainLayout.asset, Assets/Script/Data/SaveController.cs, Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Scenes/EventScene/StigmaScene/StigmaSceneController.cs, Assets/Script/Scenes/EventScene/UpgradeScene/UpgradeSceneController.cs
=> 전당 관련 기능 누락 커밋

Assets/Scenes/EventScene.unity
=> fix : 이벤트 씬 UI 오류 수정

Assets/Animation/Unit/중갑병_타락/SpriteSheet/standard_cor_sword_attack-Sheet.png.meta, Assets/Animation/Unit/중갑병_타락/SpriteSheet/standard_cor_sword_hit-Sheet.png.meta, Assets/Animation/Unit/처형자_타락/SpriteSheet/standard_cor_hook_hit-Sheet.png.meta, Assets/Animation/Unit/처형자_타락/standard_hook_cor_breathe.anim, Assets/Script/Manager/SoundManager.cs
=> 리소스 수정 및 버그 수정

Assets/Resources/Prefabs/UI/Popup/UI_UnitInfo.prefab, Assets/Script/Data/SaveController.cs, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Scenes/EventScene/UpgradeScene/UpgradeSceneController.cs, Assets/Script/UI/Popup/UI_MyDeck.cs, Assets/Script/UI/Popup/UI_UnitInfo.cs, Assets/Script/UI/Scene/UI_ProgressSummary.cs, Assets/Script/UI/Sub/UI_Card.cs, Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/DeckUnit.cs, Assets/Script/Utils/Define.cs
> 강화 3회 제한, 니므롯 진척도 연결 / 각 커밋에 상세 설명
> 로컬 테스트 완료
=> 강화 횟수 제한 및 UI 표기

Assets/Resources/Prefabs/필드_규격_임시_프리팹.prefab, Assets/Scenes/BattleScene.unity, Assets/Script/Manager/BattleManager/BattleManager.cs
> - 니므롯전 진입 시 맵 레이아웃 변경
> 로컬 테스트 완료
=> fix : 니므롯전 맵 레이아웃 변경

Assets/AddressableAssetsData/link.xml, Assets/AddressableAssetsData/link.xml.meta, Assets/Resources/Prefabs/UI/Popup/UI_Conversation.prefab, Assets/Resources/Prefabs/UI/Popup/UI_MyDeck.prefab, Assets/Resources/Prefabs/UI/Popup/UI_StigmaSelectBlocker.prefab, Assets/Resources/Prefabs/UI/Popup/UI_UnitInfo.prefab, Assets/Scenes/BattleScene.unity, Assets/Scenes/CutScene.unity, Assets/Scenes/DifficultySelectScene.unity, Assets/Scenes/EndingCreditScene.unity, Assets/Scenes/EventScene.unity, Assets/Scenes/LogoScene.unity, Assets/Scenes/MainScene.unity, Assets/Scenes/ProgressShopScene.unity, Assets/Scenes/StageSelectScene.unity, Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/UI/Hover/UI_SkillHover.cs, Assets/Script/UI/Popup/UI_TextHover.cs, Assets/Script/UI/Popup/UI_Tutorial.cs, Assets/Script/Utils/CameraScaleCtrl.cs.meta
=> fix: 해상도 대응 완료

Assets/Script/Scenes/MainScene/MainSceneController.cs
> 전당 유닛 강화수치 및 낙인 반영 안되는 버그 해결
> 로컬 테스트 완료
=> 전당 유닛 강화수치 및 낙인 반영 안되는 버그 해결

Assets/Resources/Prefabs/UI/Scene/UI_Info.prefab, Assets/Resources/Prefabs/UI/Sub/StigmaDescription.prefab
=> Info UI 수정

Assets/Script/UI/Popup/UI_MyDeck.cs
=> 타락 성흔과 보스 문제 수정

Assets/Script/Manager/BattleManager/BattleManager.cs, Assets/Script/Manager/GameManager.cs, Assets/Script/Scenes/StageSelectScene/StageCameraController.cs, Assets/Script/Unit/UnitAction/UnitAction_Savior.cs
=> 버그 수정 및 GM 기능 수정

Assets/Script/Unit/UnitAction/UnitAction_Savior.cs
> 구원자 대미지가 안 들어가는 버그 수정
> 로컬 테스트
=> 구원자 대미지가 안 들어가는 버그 수정

Assets/Resources/Prefabs/Stigma/Stigma_HandOfGrace.prefab, Assets/Resources/ScriptableObject/UnitDataSO/전령.asset
=> 전령 성흔을 은혜의 손길로 수정

Assets/Resources/ScriptableObject/UnitDataSO/장의사.asset, Assets/Resources/ScriptableObject/UnitDataSO/척후병.asset
=> SO 이미지 오류 수정

Assets/Script/Unit/BattleUnit.cs, Assets/Script/Unit/Buff/SubBuff/Buff_AfterAttackDead.cs, Assets/Script/Unit/UnitBuff.cs
=> 타락과 동시에 사망 시 버그 수정

Assets/Script/Manager/BattleManager/BattleDataManager.cs, Assets/Script/Unit/UnitAction/UnitAction.cs, Assets/Script/Unit/UnitAction/UnitAction_Appaim.cs, Assets/Script/Unit/UnitAction/UnitAction_Arabella.cs, Assets/Script/Unit/UnitAction/UnitAction_Arabella.cs.meta, Assets/Script/Unit/UnitAction/UnitAction_CenteredSplash.cs, Assets/Script/Unit/UnitAction/UnitAction_FlowerOfSacrifice.cs, Assets/Script/Unit/UnitAction/UnitAction_Laser.cs, Assets/Script/Unit/UnitAction/UnitAction_Libiel.cs, Assets/Script/Unit/UnitAction/UnitAction_Libiel.cs.meta, Assets/Script/Unit/UnitAction/UnitAction_Phanuel.cs, Assets/Script/Unit/UnitAction/UnitAction_RaquelLeah.cs, Assets/Script/Unit/UnitAction/UnitAction_Tubalcain.cs, Assets/Script/Unit/UnitAction/UnitAction_Yohrn.cs, Assets/Script/Unit/UnitAction/UnitAction_Yohrn.cs.meta, Packages/manifest.json
=> 신규 유닛 유닛액션

Assets/Locale/Tables/System/SystemTable Shared Data.asset, Assets/Locale/Tables/System/SystemTable_en.asset, Assets/Locale/Tables/System/SystemTable_ko.asset, Assets/Locale/Tables/UI/UITable Shared Data.asset, Assets/Locale/Tables/UI/UITable_en.asset, Assets/Locale/Tables/UI/UITable_ko.asset, Assets/Resources/Prefabs/UI/Popup/UI_UnitInfo.prefab, Assets/Scenes/BattleScene.unity, Assets/Script/Manager/BattleManager/BattleCutSceneController.cs, Assets/Script/Manager/BattleManager/CameraHandler.cs, Assets/Script/Scenes/ProgressShopScene/ProgressShopManager.cs, Assets/Script/UI/Popup/UI_CurrentHallUnit.cs, Assets/Script/UI/Popup/UI_MyDeck.cs, Assets/Script/UI/Popup/UI_UnitInfo.cs, Assets/Script/UI/Scene/UI_ProgressSummary.cs
=> 호버 추가 및 UIPOPUP 버그 수정
